name: Port Test
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  port-test:
    name: Outputs Test
    runs-on: macos-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn install

      - name: Setup ngrok # Download ngrok
        run: |
          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-darwin-amd64.zip
          unzip ./ngrok-stable-darwin-amd64.zip
          ./ngrok --version

      - name: Run ngrok # Run in background to continue to next step
        run: ./ngrok http 4000 > output.log 2>&1 &

      - name: Wait for ngrok # Wait for ngrok to setup
        run: sleep 5;

      - name: Env ngrok # Extract its URL
        run: |
          NGROK_URL=$(curl -s localhost:4040/api/tunnels/command_line | jq --raw-output .public_url)
          echo "::set-env name=NGROK_URL::$NGROK_URL"
          echo $NGROK_URL

      - name: Run service # Run express server, it kills itself in 60s, letting the action end
        run: node index.js
